name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  elint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1.2.1
      - name: Build elint
        run: go build -o ./.bin/elint ./.elint/cmd/elint
      - name: Run elint
        run: ./.bin/elint
